### ISSUE TITLE
Preguntas Changes

### ISSUE THREAD

**Issue by ecristerna** [ecristerna/focus-ios#72]
- [x] Campo título
- [x] Hasta 20 opciones
- [x] Selección Única, como lista o como combo (la forma de mos

![img_9681](https://cloud.githubusercontent.com/assets/3680271/20871556/a67025ba-ba5c-11e6-94af-12aa56e6bc84.PNG)
trar las opciones)

![img_9683](https://cloud.githubusercontent.com/assets/3680271/20871561/abbcf48a-ba5c-11e6-8240-d1851db58c8a.PNG)

**Comment by carodelatorrehdz** [comment]
1. Título
2. Video/imagen
3. Pregunta
